// Generated by simple:form

import type { SafeParseReturnType, ZodRawShape } from "zod";
import { validateForm, createFormStore, type FormStore } from "simple:form";
import { createContext, useContext, type ComponentProps } from "react";
import { useStore } from "@nanostores/react";

const FormContext = createContext<FormStore>(createFormStore({}));

export function useFormStore() {
  const formStore = useContext(FormContext);
  return useStore(formStore);
}

export function Form({
  children,
  validator,
  ...formProps
}: {
  validator: ZodRawShape;
} & Omit<ComponentProps<"form">, "method" | "onSubmit">) {
  const formStore = createFormStore(validator);

  return (
    <FormContext.Provider value={formStore}>
      <form
        onSubmit={(e) => {
          e.preventDefault();
          const formData = new FormData(e.target as HTMLFormElement);
          const parsed = validateForm(formData, validator);
          if (parsed.success === true) return;

          e.stopPropagation();
          formStore.setValidationErrors(parsed.error);
        }}
        {...formProps}
        method="POST"
      >
        {children}
      </form>
    </FormContext.Provider>
  );
}

export function Input(inputProps: ComponentProps<"input"> & { name: string }) {
  const store = useContext(FormContext);
  const $store = useFormStore();
  const inputState = $store.fields[inputProps.name];
  if (!inputState) {
    throw new Error(
      `Input "${inputProps.name}" not found in form. Did you use the <Form> component with your validator?`
    );
  }

  const { hasErrored, validationErrors, validator } = inputState;

  function setValidation(parsed: SafeParseReturnType<unknown, unknown>) {
    if (parsed.success === false) {
      return store.setFieldState(inputProps.name, {
        hasErrored: true,
        validationErrors: parsed.error.errors.map((e) => e.message),
        validator,
      });
    }
    store.setFieldState(inputProps.name, {
      validationErrors: [],
      hasErrored,
      validator,
    });
  }

  return (
    <>
      <input
        {...inputProps}
        onBlur={(e) => {
          if (e.target.value === "") return;
          setValidation(validator.safeParse(e.target.value));
        }}
        onChange={(e) => {
          if (!hasErrored) return;
          setValidation(validator.safeParse(e.target.value));
        }}
      />
      {validationErrors.map((e) => (
        <p className="text-red-400" key={e}>
          {e}
        </p>
      ))}
    </>
  );
}
